### ISSUE TITLE
Linux (and macOS) support

### ISSUE THREAD

**Issue by gabrc52** [libgenapps/LibgenDesktop#24]
On Linux, I've ran the program (using `mono`) and gotten the following error message:

`The entry point method could not be loaded due to Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`

Mono also supports Mac OS so supporting both OS's can be done with the same effort.

**Comment by libgenapps** [comment]
`PresentationFramework` is the main WPF assembly. Mono doesn't have support for WPF and I don't think it will ever have because WPF depends on too many components available only for Windows (e.g. DirectX).

Also take a look at these discussions: https://github.com/libgenapps/LibgenDesktop/issues/5, https://github.com/libgenapps/LibgenDesktop/issues/8, https://github.com/libgenapps/LibgenDesktop/issues/9, and https://github.com/libgenapps/LibgenDesktop/issues/20.
