### ISSUE TITLE
Database not "synchronizing" possible Bug

### ISSUE THREAD

**Issue by Elpuma** [libgenapps/LibgenDesktop#28]
- [x] I understand that feature requests are no longer accepted except for those listed here: https://github.com/libgenapps/LibgenDesktop/issues/27

Choose one of the following:
- [X] this is a bug report;
- [ ] this is a new translation suggestion.

When I "synchronize" the database, only "Non-Fiction-Book list" is updated, but the section of "Scientific Articles or white papers" is not synchronized, is it really not updating that section or is it visual?

![image](https://user-images.githubusercontent.com/3074185/81743154-7a6caa80-945e-11ea-954b-bd5bc83af46e.png)

**Comment by libgenapps** [comment]
Yes, this is correct. Unfortunately, the server doesn't provide any support for synchronizing other collections. The only way to update them is to import the new database dump. Such import should be a little bit faster than the initial import because Libgen Desktop will import only the new and changed entries and skip the rest.
