### ISSUE TITLE
Database locked when Opening Database created with 32 bits version

### ISSUE THREAD

**Issue by Elpuma** [libgenapps/LibgenDesktop#29]
- [X] I understand that feature requests are no longer accepted except for those listed here: https://github.com/libgenapps/LibgenDesktop/issues/27

Choose one of the following:
- [X] this is a bug report;
- [ ] this is a new translation suggestion.

When you use 64 bits version and try to open an existing database created using the 32 bits client, when you try to "synchronize" it will show a "database is locked error" interrupting and failing the synchronization attempt. It is not happening on the 32 bits version opening a database created on the 64 bits version.

**Comment by libgenapps** [comment]
One database can be opened only in one instance of Libgen Desktop. Could you please make sure you are running only one instance of the app and try again?

**Comment by libgenapps** [comment]
Are the following reproduction items correctly describe the steps to reproduce the issue?
1. Start the 32-bit version of the app.
2. Create an empty database.
3. Close the 32-bit version.
4. Start the 64-bit version.
5. Import the latest non-fiction dump.
6. Try to synchronize the non-fiction collection.

Database is locked message appears.

If that's correct, then it is strange that you were able to create an empty database because starting from 1.4 it is very difficult (while not completely impossible) to do so. Could you please elaborate on how did you create an empty database in the 32-bit version of the app?

**Comment by Elpuma** [comment]
I want to close the issue confirming that the error has not ocurred again. It was a corrupted database.
