### ISSUE TITLE
Library Genesis for Linux

### ISSUE THREAD

**Issue by aurora-of-earth** [libgenapps/LibgenDesktop#5]
How about developing a client for the Linux platform?

You can at least write this app with the <a href="https://en.wikipedia.org/wiki/Mono_(software)">"Mono Framework</a>, so it could run on Linux too.

**Comment by dansef** [comment]
Just use the Net Core its easy to port for all platforms

**Comment by dentarthur** [comment]
Looking forward to the port!

Is anybody integrating with:

1. Zotero
2. Calibre
3. Libgen librarian cataloguer (ie editing entries)
4. P2P online networks
5. P2P anonymous soffline physical sneakernet (circulating HDDs as token ring)

When those are done the combination should survive any attack due to mass dispersal!

Growing censorship makes it look increasingly vulnerable until they are done.

Then needs further project for recoonstructing a distributed corecore if loses centralized base area.

A "Republic of Letters Project" for robust and resilient decentralized submissions and catalog editing via publish and subscribe message oriented middleware. Could be side channels to Massively Multiplayer Online Role Playing Games (MMORPGs) also used for game communications and development.

Sorry I am not a developer and cannot contribute except perhaps docs.

Anyway thanks and congratulations to all the librarians, developers, admins and other contributors for brilliant work done!

**Comment by libgenapps** [comment]
As far as I know, neither Mono nor .NET Core support WPF (Windows Presentation Foundation) heavily used by Libgen Desktop. There is another project, https://github.com/libgenapps/LibgenServer (currently in development) that will be cross-platform.

**Comment by aurora-of-earth** [comment]
@libgenapps 
Rewrite the app, for Library Genesis and Linux both promote liberty.
You can write a core command-line cross-platform client written in C++ and another cross-platform GUI frontend written via GTK or Qt.

**Comment by libgenapps** [comment]
@aurora-of-earth, I do not represent Library Genesis. However if you or anybody else are willing to implement Linux support and create a pull request, I would be happy to merge it.

**Comment by aurora-of-earth** [comment]
@libgenapps Merge what? the whole framework is not supported on the Linux platform.
At the very least, you can test if the software is compatible with <a href="https://en.wikipedia.org/wiki/Wine_(software)">WINE</a>.

**Comment by libgenapps** [comment]
@aurora-of-earth, as far as I know, WINE relies on Mono to run any .NET applications and Mono itself doesn't support WPF (which in turn requires DirectX and quite a lot of Windows Runtime components). But like you said, you or someone else can create a separate implementation of the app using C++ and GTK/Qt and send me a pull request with the proposed changes. I will be happy to accept such pull request and merge it into the master branch of the repository.

**Comment by aurora-of-earth** [comment]
@libgenapps Yes I'll do that.
